name: Request a Tenant in APP3 environment
description: Create a tenant request
title: "[APP3-TENANT]: "
labels: ["app3-tenant"]
# assignees:
#   - sumesh-aot
body:
  - type: markdown
    attributes:
      value: |
        <span style="color: red">
        Please note this ticket will create a tenant in **APP3** environment. Only continue if you need a tenant in APP3 environment, this environment is used for demo purpose and not for development integration testing.
        </span>

  - type: input
    id: business_name
    attributes:
      label: Business Name
      description: Unique business name (limit to 50 characters)
      placeholder: ex. My Business
    validations:
      required: true
  - type: input
    id: application_name
    attributes:
      label: Application Name
      description: Application name which will be displayed to users as title (limit to 50 characters)
      placeholder: ex. My Application Name
    validations:
      required: true
  - type: input
    id: tenant_key
    attributes:
      label: Tenant Key
      description: Unique tenant key without <b>any spaces and in small characters</b> (limit to 10 characters)
      placeholder: ex. demo
    validations:
      required: true
  - type: textarea
    id: business_purpose
    attributes:
      label: Description of your business
      description: Please give a brief on your business
      placeholder: Tell us what you are trying to achive with formsflow!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: How can we contact you ?
      description: Please give your email address
      placeholder: demo@eample.com
    validations:
      required: true
