name: Tenant Request

on:
  issues:
    types: [opened, edited]
jobs:
  create-tenant:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add initial comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            We are working on it :sparkles: Thank you for your interest! :sparkles:
            
      - name: Parse issue
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser

      - name: Create tenant
        id: create-tenant
        env:
          PAYLOAD: '{"key": "${{ fromJson(steps.issue-parser.outputs.jsonString).tenant_key }}", "name": "${{ fromJson(steps.issue-parser.outputs.jsonString).tenant_name }}", "createDefaultUsers": true, "details": {"applicationTitle": "${{ fromJson(steps.issue-parser.outputs.jsonString).tenant_title}}", "roles": [] } }'
       # uses: wei/curl@master
       # with:
       #   args: -X POST '${{ secrets.TENANT_ENDPOINT }}' -H 'content-type:application/json' -d '${{env.PAYLOAD}}'
        run: |
          echo "::set-output name=curl_response::$(curl -X POST '${{ secrets.TENANT_ENDPOINT }}' -H 'content-type:application/json' -d '${{env.PAYLOAD}}')"
      - name: Update Result
        run: |
          echo "${{ steps.create-tenant.outputs.curl_response.value }}"

        
