name: Tenant Request

on:
  issues:
    types: [opened]
jobs:
  add-initial-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            We are working on it :sparkles: Thank you for your interest! :sparkles:
            
      - name: Parse issue
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser

      - run: |
          echo '${{ steps.issue-parser.outputs }}'
          curl -X POST ${{ env.TENANT_ENDPOINT }} -d '{"key": ${{ steps.issue-parser.outputs["tenant_key"] }}, "name": ${{ steps.issue-parser.outputs["tenant_name"] }}, "details": {"applicationTitle": ${{ steps.issue-parser.outputs["tenant_title"]}} } }'

